### ISSUE TITLE
Some questions about some part of context.

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#10]
Hi Matt!
As we are translating this content, some misunderstanding may occur for us and we need you to explain about them.
In this issue, I will ask some questions. Hope these questions and answers help us to improve the translation.
Please don't close the issue. I intend to close it after the completion of the translation and resolving ambiguities.

**Comment by SMSadegh19** [comment]
> Millions in jail without trial or conviction. Ethnic minorities rounded up in genocidal numbers. Babies in cages. Is this what freedom looks like?

What's the meaning and purpose of **Babies in cages**?
Is it an idiom in English? or does it refer to a special happening? or what?
Is it very clear to English readers around the world?
Isn't there any need to explain more about this phrase for English readers?

**Comment by SMSadegh19** [comment]
Hi!
And my 2nd question.
> If we drill into individual age groups, it is almost impossible to find a meaningful comparison to American incarceration in public data.

I can't understand and translate this paragraph.
What's the meaning of this sentence? Can you explain more?

Thanks a lot! ❤️

**Comment by mkorostoff** [comment]
> What's the meaning and purpose of Babies in cages?

- https://www.azcentral.com/story/news/politics/immigration/2014/06/18/arizona-immigrant-children-holding-area-tour/10780449/
- https://www.youtube.com/watch?v=glpE_m8OE2A
- https://www.splcenter.org/news/2020/06/17/family-separation-under-trump-administration-timeline

> If we drill into individual age groups...

The incarceration rate in America is high. If we examine specific age groups, the rate is even higher. The incarceration rate for black men age 30 to 34 is around 10%. There is no other country that publicly admits to such a high incarceration rate. The only data that come even close are estimates for secret prisons in China and North Korea, but even _these_ are still smaller than American incarceration.

**Comment by mkorostoff** [comment]
p.s @SMSadegh19 if you [@ mention me](https://github.blog/2011-03-23-mention-somebody-they-re-notified/) I'll see these threads a lot faster
