### ISSUE TITLE
Feature request: progress bar for main context. (Keep people away from procrastination in reading)

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#12]
Hi @MKorostoff! We have completed the translation of this project into Persian. Before we promote this webpage in public, we’ve sent it to about 20 people to see it for testing and get feedback.
Most of them had a problem. They thought that the counter of prisoners must reach 2.3 million to finish the context. So they went a little further and thought that a lot of the text would be left and gave up, while on my desktop computer, the content ends at 780,000 prisoners, and on my mobile phone, the finish point is at about 230,000 prisoners.
Some of my friends thought the project was bigger than it actually was, so they procrastinated a bit or postponed the reading of the content.

For example, a friend said:

> I read it on the desktop to the point that we reach 600,000 prisoners and I thought I should go to 2.3 million to finish the content. So I gave up and postponed the reading of the rest of the content to another time. Whereas if I knew it would finish at 700,000, I keep it going to the endpoint.

I think it is good to fix this problem in any way. One idea is to add a progress bar that shows how much the reader has come from the main content and how much is left.
Or maybe you suggest and implement another idea to fix this problem.
Actually, the problem is originated from the unconscious thinking of people about the number of prisoners and the counter of prisoners.

**Comment by mkorostoff** [comment]
Maybe it would work to just put some text like "reading time: about 15 minutes" on the main title screen, instead of a dynamic progress bar. I don't really expect people to finish the content, and 90% of the emotional impact is in the first 5 seconds, but maybe it would help. What do you think?

**Comment by SMSadegh19** [comment]
Hi Matt!

I didn't pay attention to `emotional impact is in the first 5 seconds`. It's a good point.

I think `reading time: about 15 minutes` is a good idea.

**Comment by mkorostoff** [comment]
After thinking about this more, I've decided I like the way it is currently.
