### ISSUE TITLE
Adding Persian translation

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#13]
Hi @MKorostoff !
We translated this project into [Persian/فارسی](https://persianhodhod.ir/prisoners/) .
As you told ( #7 ), You'll make us happy to add the link to the readme.
And thank you a lot for your lovely project.❤️

**Comment by mkorostoff** [comment]
@SMSadegh19 thanks! Looks awesome, must have taken a lot of work. Link added in 5ab4ac6.

**Comment by SMSadegh19** [comment]
Thanks a lot!❤️
