### ISSUE TITLE
A question about license of this projcet.

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#5]
Hello Mr Korostoff!
I really love this project! wonderfull!
And I didn't see license file in this project.
Can I fork it and translate into another language?

**Comment by mkorostoff** [comment]
@SMSadegh19 thanks for the reminder, just added [GPL3 license](https://github.com/MKorostoff/incarceration-in-real-numbers/blob/master/LICENSE.txt). Feel free to copy, adapt, translate, or sell derivative open-source works.
