### ISSUE TITLE
Feature request: allow translations and provide instructions.

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#7]
Hi! @MKorostoff
As we (Me and a teammate) started translating this project into Persian, It will be pleasant for me if you enable translation instructions like [1-pixel-wealth translation instructions](https://github.com/MKorostoff/1-pixel-wealth/issues/8#issuecomment-622964168).
"I love your project so much"; I needed to restate.

**Comment by mkorostoff** [comment]
@SMSadegh19 you can use the same translation strategy for this website that is used on 1 pixel wealth: fork the repository, edit index.html, then publish with GitHub pages.
